spring:
  base-url: http://localhost:8080
  application:
    name: finance_buddy

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/finance_buddy
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: sa
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google: # Google OAuth2 설정
            client-id: awefa23ta23ga34
            client-secret: awegawegawegaw
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google" # 로그인 후 리다이렉트 URL
            client-name: Google
          naver:
            client-id: ga3ga34gae4g
            client-secret: a34ga34ga34g
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            provider: naver
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.id

